import { render } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import manifest from '../manifest.json';
import * as api from './index';
import type { IconComponent } from './createIcon';

/**
 * Whole-set guarantees. Every icon is generated by the same factory, so these
 * hold for all of them or the codegen has a hole — which is exactly the thing
 * a per-icon test would be too tedious to catch.
 */
const exported = Object.entries(api).filter(([name]) => name.startsWith('Icon')) as [
  string,
  IconComponent,
][];

describe('the icon set', () => {
  it('exports exactly the icons the manifest lists', () => {
    expect(exported.map(([name]) => name).sort()).toEqual(
      manifest.icons.map((icon) => icon.name).sort(),
    );
    expect(manifest.count).toBe(manifest.icons.length);
  });

  it('ships a non-empty set', () => {
    expect(exported.length).toBeGreaterThan(0);
  });

  it.each(exported)('%s renders a sized, decorative svg', (name, Icon) => {
    const { container } = render(<Icon />);
    const svg = container.querySelector('svg');

    expect(svg).not.toBeNull();
    expect(svg).toHaveAttribute('viewBox');
    expect(svg).toHaveAttribute('aria-hidden', 'true');
    expect(svg).toHaveClass('ui-icon');
    expect(svg?.style.width).toBe('1em');
    expect(svg?.childElementCount).toBeGreaterThan(0);
  });

  it.each(exported)('%s paints from currentColor only', (_name, Icon) => {
    const { container } = render(<Icon />);
    const markup = container.innerHTML;

    // A literal paint would ignore the consumer's `color` — the one thing the
    // whole package promises.
    expect(markup).not.toMatch(/(?:fill|stroke)="#/);
    expect(markup).not.toMatch(/(?:fill|stroke)="rgb/);
  });

  it.each(exported)('%s takes an accessible name on demand', (name, Icon) => {
    const { container } = render(<Icon title={name} />);
    const svg = container.querySelector('svg');

    expect(svg).toHaveAttribute('role', 'img');
    expect(svg?.querySelector('title')).toHaveTextContent(name);
  });

  it.each(exported)('%s names itself for devtools', (name, Icon) => {
    expect(Icon.displayName).toBe(name);
  });

  it('carries no ids, which would collide across repeated instances', () => {
    const { container } = render(
      <>
        {exported.map(([name, Icon]) => (
          <Icon key={name} />
        ))}
      </>,
    );

    expect(container.querySelectorAll('[id]')).toHaveLength(0);
    expect(container.innerHTML).not.toContain('url(#');
  });
});
