/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */

/**
 * The `size.icon-*` ramp, smallest first. Note the order is **not**
 * alphabetical — `xxl` (28px) sits between `lg` (24px) and `xl` (32px).
 *
 * Each step is a token `var()` with the token's own value as the fallback, so
 * icons are sized correctly even in an app that never loads the tokens CSS.
 */
export const ICON_SIZES = {
  xxs: 'var(--ui-size-icon-xxs, 0.75rem)',
  sm: 'var(--ui-size-icon-sm, 1rem)',
  md: 'var(--ui-size-icon-md, 1.25rem)',
  lg: 'var(--ui-size-icon-lg, 1.5rem)',
  xxl: 'var(--ui-size-icon-xxl, 1.75rem)',
  xl: 'var(--ui-size-icon-xl, 2rem)',
} as const;

/** Named steps accepted by `IconProps['size']`. */
export type IconSize = keyof typeof ICON_SIZES;
