/**
 * Generates dist/tokens.{css,scss,js,d.ts,cjs,d.cts} from src/tokens.json.
 *
 * src/tokens.json is the design system's export and is treated as READ-ONLY:
 * it is reproduced verbatim, including tokens whose value is `null` ("no Figma
 * counterpart - kept as placeholder"). Those are SKIPPED rather than emitted —
 * `--ui-x: null` is invalid CSS and would break the whole declaration block.
 * Components reach the affected values with `var(--token, fallback)`, so the
 * moment a placeholder gains a real value the fallback goes inert on its own.
 *
 * Two layers: primitives (grey.500, space.4 — raw values, no meaning) and
 * semantic tokens, which live under `<platform>.<scheme>.color.*`. Semantic
 * names are emitted WITHOUT their platform/scheme prefix so component CSS is
 * written once and re-themed entirely by selectors:
 *
 *   :root                                   primitives + web light defaults
 *   [data-theme="light"]                    web light (re-declared, so a light
 *                                           island inside dark re-themes)
 *   [data-theme="dark"]                     web dark
 *   [data-platform="mobile"]                mobile light
 *   [data-platform="mobile"][data-theme="dark"]   mobile dark
 */
import StyleDictionary from 'style-dictionary';

const REF = /^\{([^}]+)\}$/;

const PLATFORMS = ['web', 'mobile'];
const SCHEMES = ['light', 'dark'];

const isPlatformToken = (token) => PLATFORMS.includes(token.path[0]);

/** Semantic tokens drop their `<platform>.<scheme>` prefix: web.light.color.text.primary → color-text-primary */
const semanticPath = (path) => path.slice(2);

// Dots are not valid in a CSS identifier, so `space.0.5` must emit as
// --ui-space-0-5; left unescaped the whole declaration is dropped by browsers.
const cssName = (path) => ['ui', ...path].join('-').replace(/\./g, '-');

/** A token is emitted only when it has a real value; `null` placeholders are skipped. */
const hasValue = (token) => token.value !== null && token.value !== undefined;

/**
 * Pure references render as var() so the primitive → semantic chain survives
 * into the emitted CSS instead of being flattened to hex values.
 */
const cssValue = (token) => {
  const match = String(token.original.value).match(REF);
  return match ? `var(--${cssName(match[1].split('.'))})` : token.value;
};

const banner = '/* Generated by @vegam-ui/tokens. Do not edit. */';

StyleDictionary.registerFormat({
  name: 'css/ui-theme',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(hasValue);
    const globals = tokens.filter((token) => !isPlatformToken(token));

    const semantic = (platform, scheme) =>
      tokens.filter(
        (token) => token.path[0] === platform && token.path[1] === scheme && isPlatformToken(token),
      );

    const line = (token, path) => `  --${cssName(path)}: ${cssValue(token)};`;
    const globalLine = (token) => line(token, token.path);
    const semanticLine = (token) => line(token, semanticPath(token.path));

    // Every scheme/platform combination must declare the same token set, or a
    // component reads a variable that only exists in one theme.
    const nameSet = (list) => new Set(list.map((token) => cssName(semanticPath(token.path))));
    const base = nameSet(semantic('web', 'light'));
    for (const platform of PLATFORMS) {
      for (const scheme of SCHEMES) {
        if (platform === 'web' && scheme === 'light') continue;
        for (const token of semantic(platform, scheme)) {
          const name = cssName(semanticPath(token.path));
          if (!base.has(name)) {
            throw new Error(
              `${platform}.${scheme} declares --${name}, which web.light does not — semantic sets must match`,
            );
          }
        }
      }
    }

    const block = (selector, lines, scheme) =>
      lines.length === 0
        ? []
        : [`${selector} {`, ...(scheme ? [`  color-scheme: ${scheme};`] : []), ...lines, '}', ''];

    return [
      banner,
      ':root {',
      ...globals.map(globalLine),
      ...semantic('web', 'light').map(semanticLine),
      '}',
      '',
      ...block('[data-theme="light"]', semantic('web', 'light').map(semanticLine), 'light'),
      ...block('[data-theme="dark"]', semantic('web', 'dark').map(semanticLine), 'dark'),
      ...block('[data-platform="mobile"]', semantic('mobile', 'light').map(semanticLine), 'light'),
      ...block(
        '[data-platform="mobile"][data-theme="dark"]',
        semantic('mobile', 'dark').map(semanticLine),
        'dark',
      ),
    ].join('\n');
  },
});

StyleDictionary.registerTransform({
  name: 'name/ui-kebab',
  type: 'name',
  transform: (token) => cssName(token.path),
});

const camelName = (path) => {
  const parts = path.flatMap((segment) => String(segment).split(/[-.]/));
  return parts
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
};

StyleDictionary.registerTransform({
  name: 'name/ui-camel',
  type: 'name',
  transform: (token) => camelName(token.path),
});

const jsBanner = '/** Generated by @vegam-ui/tokens. Do not edit. */';

/** JS consumers get resolved values; placeholders are omitted entirely. */
const jsTokens = (dictionary) => dictionary.allTokens.filter(hasValue);

StyleDictionary.registerFormat({
  name: 'javascript/ui-esm',
  format: ({ dictionary }) =>
    [
      jsBanner,
      ...jsTokens(dictionary).map(
        (token) => `export const ${token.name} = ${JSON.stringify(token.value)};`,
      ),
      '',
    ].join('\n'),
});

StyleDictionary.registerFormat({
  name: 'typescript/ui-esm-declarations',
  format: ({ dictionary }) =>
    [
      jsBanner,
      ...jsTokens(dictionary).map(
        (token) =>
          `export declare const ${token.name}: ${typeof token.value === 'number' ? 'number' : 'string'};`,
      ),
      '',
    ].join('\n'),
});

StyleDictionary.registerFormat({
  name: 'javascript/ui-cjs',
  format: ({ dictionary }) =>
    [
      jsBanner,
      "'use strict';",
      'module.exports = {',
      ...jsTokens(dictionary).map((token) => `  ${token.name}: ${JSON.stringify(token.value)},`),
      '};',
      '',
    ].join('\n'),
});

StyleDictionary.registerFormat({
  name: 'typescript/ui-cjs-declarations',
  format: ({ dictionary }) =>
    [
      jsBanner,
      'declare const tokens: {',
      ...jsTokens(dictionary).map(
        (token) => `  ${token.name}: ${typeof token.value === 'number' ? 'number' : 'string'};`,
      ),
      '};',
      'export = tokens;',
      '',
    ].join('\n'),
});

StyleDictionary.registerFormat({
  name: 'scss/ui-variables',
  format: ({ dictionary }) =>
    [
      '// Generated by @vegam-ui/tokens. Do not edit.',
      ...jsTokens(dictionary).map((token) => `$${cssName(token.path)}: ${token.value};`),
      '',
    ].join('\n'),
});

const sd = new StyleDictionary({
  source: ['src/tokens.json'],
  // Placeholder tokens are intentional in the source; do not warn about them.
  log: { verbosity: 'silent', warnings: 'disabled' },
  platforms: {
    css: {
      transforms: ['name/ui-kebab'],
      buildPath: 'dist/',
      files: [{ destination: 'tokens.css', format: 'css/ui-theme' }],
    },
    scss: {
      transforms: ['name/ui-kebab'],
      buildPath: 'dist/',
      files: [{ destination: 'tokens.scss', format: 'scss/ui-variables' }],
    },
    js: {
      transforms: ['name/ui-camel'],
      buildPath: 'dist/',
      files: [
        { destination: 'tokens.js', format: 'javascript/ui-esm' },
        { destination: 'tokens.d.ts', format: 'typescript/ui-esm-declarations' },
        { destination: 'tokens.cjs', format: 'javascript/ui-cjs' },
        { destination: 'tokens.d.cts', format: 'typescript/ui-cjs-declarations' },
      ],
    },
  },
});

await sd.buildAllPlatforms();
