/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconDelete = createIcon(
  'IconDelete',
  '0 0 16 16',
  <>
    <path d="M3 5H13M6 5V3.5H10V5M5.5 5L6 12.5H11L11.5 5" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
  </>,
);
