/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconSearch = createIcon(
  'IconSearch',
  '0 0 16 16',
  <>
    <path d="M6.5 10.5C8.70914 10.5 10.5 8.70914 10.5 6.5C10.5 4.29086 8.70914 2.5 6.5 2.5C4.29086 2.5 2.5 4.29086 2.5 6.5C2.5 8.70914 4.29086 10.5 6.5 10.5Z" stroke="currentColor" strokeWidth="1.25" />
    <path d="M10 10L14 14" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" />
  </>,
);
