/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconBack = createIcon(
  'IconBack',
  '0 0 16 16',
  <>
    <path d="M10 4L6 8L10 12" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
  </>,
);
