/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconLock = createIcon(
  'IconLock',
  '0 0 16 16',
  <>
    <path d="M11.5 7H4.5C3.67157 7 3 7.67157 3 8.5V12.5C3 13.3284 3.67157 14 4.5 14H11.5C12.3284 14 13 13.3284 13 12.5V8.5C13 7.67157 12.3284 7 11.5 7Z" stroke="currentColor" strokeWidth="1.25" />
    <path d="M5 7V5.5C5 4.70435 5.31607 3.94129 5.87868 3.37868C6.44129 2.81607 7.20435 2.5 8 2.5C8.79565 2.5 9.55871 2.81607 10.1213 3.37868C10.6839 3.94129 11 4.70435 11 5.5V7" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" />
    <path d="M8 11.5C8.55228 11.5 9 11.0523 9 10.5C9 9.94772 8.55228 9.5 8 9.5C7.44772 9.5 7 9.94772 7 10.5C7 11.0523 7.44772 11.5 8 11.5Z" fill="currentColor" />
  </>,
);
