/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconWarning = createIcon(
  'IconWarning',
  '0 0 16 16',
  <>
    <path d="M8 2L1 14H15L8 2Z" stroke="currentColor" strokeWidth="1.25" strokeLinejoin="round" />
    <path d="M8 7V10M8 11.5V12" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" />
  </>,
);
