/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconMore = createIcon(
  'IconMore',
  '0 0 16 16',
  <>
    <path d="M4 9.25C4.69036 9.25 5.25 8.69036 5.25 8C5.25 7.30964 4.69036 6.75 4 6.75C3.30964 6.75 2.75 7.30964 2.75 8C2.75 8.69036 3.30964 9.25 4 9.25Z" fill="currentColor" />
    <path d="M8 9.25C8.69036 9.25 9.25 8.69036 9.25 8C9.25 7.30964 8.69036 6.75 8 6.75C7.30964 6.75 6.75 7.30964 6.75 8C6.75 8.69036 7.30964 9.25 8 9.25Z" fill="currentColor" />
    <path d="M12 9.25C12.6904 9.25 13.25 8.69036 13.25 8C13.25 7.30964 12.6904 6.75 12 6.75C11.3096 6.75 10.75 7.30964 10.75 8C10.75 8.69036 11.3096 9.25 12 9.25Z" fill="currentColor" />
  </>,
);
