/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconSorting = createIcon(
  'IconSorting',
  '0 0 16 16',
  <>
    <path d="M3 5H13M5 8H11M7 11H9" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" />
  </>,
);
