/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconReset = createIcon(
  'IconReset',
  '0 0 16 16',
  <>
    <path d="M3 8C3 9.18725 3.42247 10.3358 4.19181 11.24C4.96116 12.1443 6.02717 12.7453 7.19909 12.9354C8.37101 13.1256 9.57236 12.8926 10.5882 12.278C11.604 11.6634 12.368 10.7075 12.7434 9.58114C13.1189 8.45481 13.0813 7.23164 12.6373 6.1305C12.1934 5.02936 11.3722 4.12211 10.3205 3.5711C9.26889 3.02009 8.05549 2.86128 6.89746 3.12307C5.73943 3.38487 4.71235 4.0502 4 5L2 3V6H5" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
  </>,
);
