/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconFilter = createIcon(
  'IconFilter',
  '0 0 16 16',
  <>
    <path d="M2 4H14M4 8H12M6.5 12H9.5" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" />
  </>,
);
