/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconHome = createIcon(
  'IconHome',
  '0 0 16 16',
  <>
    <path d="M2 7.5L8 2L14 7.5V14H10V10.5H6V14H2V7.5Z" stroke="currentColor" strokeWidth="1.25" strokeLinejoin="round" />
  </>,
);
