/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconEdit = createIcon(
  'IconEdit',
  '0 0 16 16',
  <>
    <path d="M11 2.5L13.5 5L5.5 13H3V10.5L11 2.5Z" stroke="currentColor" strokeWidth="1.25" strokeLinejoin="round" />
  </>,
);
