/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconAdd = createIcon(
  'IconAdd',
  '0 0 16 16',
  <>
    <path d="M8 3V13M3 8H13" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" />
  </>,
);
