/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconClose = createIcon(
  'IconClose',
  '0 0 16 16',
  <>
    <path d="M4 4L12 12M12 4L4 12" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" />
  </>,
);
