/* GENERATED by scripts/build-icons.mjs — do not edit. Run `pnpm icons`. */
import { createIcon } from '../createIcon';

export const IconClock = createIcon(
  'IconClock',
  '0 0 16 16',
  <>
    <path d="M8 14C11.3137 14 14 11.3137 14 8C14 4.68629 11.3137 2 8 2C4.68629 2 2 4.68629 2 8C2 11.3137 4.68629 14 8 14Z" stroke="currentColor" strokeWidth="1.25" />
    <path d="M8 5V8L10 10" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" />
  </>,
);
